
package cn.itcast.cxf.test;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserService", targetNamespace = "http://test.cxf.itcast.cn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<cn.itcast.cxf.test.Car>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findCarsByUser", targetNamespace = "http://test.cxf.itcast.cn/", className = "cn.itcast.cxf.test.FindCarsByUser")
    @ResponseWrapper(localName = "findCarsByUserResponse", targetNamespace = "http://test.cxf.itcast.cn/", className = "cn.itcast.cxf.test.FindCarsByUserResponse")
    public List<Car> findCarsByUser(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHi", targetNamespace = "http://test.cxf.itcast.cn/", className = "cn.itcast.cxf.test.SayHi")
    @ResponseWrapper(localName = "sayHiResponse", targetNamespace = "http://test.cxf.itcast.cn/", className = "cn.itcast.cxf.test.SayHiResponse")
    public String sayHi(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
